### ISSUE TITLE
! breaks pmd

### ISSUE THREAD

**Issue by DarkVillager** [PreMiD/pmd#104]
![image](https://user-images.githubusercontent.com/42322979/227721103-48011200-a564-4bc7-b896-8e258ab7bea0.png)
```bat
C:\Users\Guus\Downloads\Gits\Presences>npx pmd
pmd Hello Dark_Ville!
? What do you want to do? Modify an existing Presence
√ Select or search for a presence to modify » osu!ppy
pmd Starting TypeScript compiler...

C:\Users\Guus\Downloads\Gits\Presences\node_modules\typescript\lib\typescript.js:10413
        return sourceFile.lineMap || (sourceFile.lineMap = computeLineStarts(sourceFile.text));
                          ^
TypeError: Cannot read properties of undefined (reading 'lineMap')
    at getLineStarts (C:\Users\Guus\Downloads\Gits\Presences\node_modules\typescript\lib\typescript.js:10413:27)
    at Object.getLineAndCharacterOfPosition (C:\Users\Guus\Downloads\Gits\Presences\node_modules\typescript\lib\typescript.js:10459:50)
    at reportDiagnostic (file:///C:/Users/Guus/Downloads/Gits/Presences/node_modules/pmd/src/actions/modify.ts:91:33)
    at Array.forEach (<anonymous>)
    at emitFilesAndReportErrors (C:\Users\Guus\Downloads\Gits\Presences\node_modules\typescript\lib\typescript.js:126128:21)
    at Object.result.afterProgramCreate (C:\Users\Guus\Downloads\Gits\Presences\node_modules\typescript\lib\typescript.js:126319:13)
    at synchronizeProgram (C:\Users\Guus\Downloads\Gits\Presences\node_modules\typescript\lib\typescript.js:126629:22)
    at Object.createWatchProgram (C:\Users\Guus\Downloads\Gits\Presences\node_modules\typescript\lib\typescript.js:126546:9)
    at file:///C:/Users/Guus/Downloads/Gits/Presences/node_modules/pmd/src/actions/modify.ts:125:4
```

**Comment by DarkVillager** [comment]
Already solved.
